// <auto-generated />
using System;
using DistopiaNetwork.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DistopiaNetwork.Server.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DistopiaNetwork.Server.Entities.PodcastEntity", b =>
            {
                b.Property<string>("PodcastId").HasMaxLength(36).HasColumnType("nvarchar(36)");
                b.Property<string>("PublisherPubKey").HasColumnType("nvarchar(MAX)").IsRequired();
                b.Property<string>("PublisherServer").HasMaxLength(64).HasColumnType("nvarchar(64)").IsRequired();
                b.Property<string>("Title").HasMaxLength(512).HasColumnType("nvarchar(512)").IsRequired();
                b.Property<string>("Description").HasMaxLength(4096).HasColumnType("nvarchar(4096)").IsRequired();
                b.Property<string>("ImageUrl").HasMaxLength(2048).HasColumnType("nvarchar(2048)");
                b.Property<string>("FileHash").HasMaxLength(64).HasColumnType("nvarchar(64)").IsRequired();
                b.Property<long>("FileSize").HasColumnType("bigint");
                b.Property<int>("DurationSeconds").HasColumnType("int");
                b.Property<long>("PublishTimestamp").HasColumnType("bigint");
                b.Property<string>("Signature").HasColumnType("nvarchar(MAX)").IsRequired();
                b.Property<DateTime>("InsertedAt").HasColumnType("datetime2");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.HasKey("PodcastId");
                b.HasIndex("FileHash").HasDatabaseName("IX_Podcasts_FileHash");
                b.HasIndex("PublishTimestamp").HasDatabaseName("IX_Podcasts_PublishTimestamp");
                b.HasIndex("PublisherServer").HasDatabaseName("IX_Podcasts_PublisherServer");
                b.ToTable("Podcasts");
            });

            modelBuilder.Entity("DistopiaNetwork.Server.Entities.CacheEntryEntity", b =>
            {
                b.Property<string>("FileHash").HasMaxLength(64).HasColumnType("nvarchar(64)");
                b.Property<string>("FilePath").HasMaxLength(1024).HasColumnType("nvarchar(1024)").IsRequired();
                b.Property<DateTime>("LastAccess").HasColumnType("datetime2");
                b.Property<DateTime>("ExpiryTimestamp").HasColumnType("datetime2");
                b.Property<string>("PodcastId").HasMaxLength(36).HasColumnType("nvarchar(36)");
                b.HasKey("FileHash");
                b.HasIndex("ExpiryTimestamp").HasDatabaseName("IX_CacheEntries_Expiry");
                b.HasIndex("PodcastId");
                b.ToTable("CacheEntries");
                b.HasOne("DistopiaNetwork.Server.Entities.PodcastEntity", "Podcast")
                    .WithMany()
                    .HasForeignKey("PodcastId")
                    .OnDelete(DeleteBehavior.SetNull);
            });
#pragma warning restore 612, 618
        }
    }
}
