// <auto-generated />
using System;
using DistopiaNetwork.PublisherClient.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DistopiaNetwork.PublisherClient.Data.Migrations
{
    [DbContext(typeof(PublisherDbContext))]
    partial class PublisherDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("DistopiaNetwork.PublisherClient.Entities.LocalEpisodeEntity", b =>
            {
                b.Property<string>("PodcastId").HasMaxLength(36).HasColumnType("TEXT");
                b.Property<string>("Title").HasMaxLength(512).HasColumnType("TEXT").IsRequired();
                b.Property<string>("Description").HasMaxLength(4096).HasColumnType("TEXT").IsRequired().HasDefaultValue("");
                b.Property<string>("FileHash").HasMaxLength(64).HasColumnType("TEXT").IsRequired();
                b.Property<string>("LocalFilePath").HasMaxLength(2048).HasColumnType("TEXT").IsRequired();
                b.Property<long>("FileSize").HasColumnType("INTEGER");
                b.Property<int>("DurationSeconds").HasColumnType("INTEGER");
                b.Property<long>("PublishTimestamp").HasColumnType("INTEGER");
                b.Property<string>("UploadStatus").HasMaxLength(32).HasColumnType("TEXT").IsRequired().HasDefaultValue("Draft");
                b.Property<DateTime>("CreatedAt").HasColumnType("TEXT");
                b.Property<DateTime?>("LastAttemptAt").HasColumnType("TEXT");
                b.Property<string>("LastErrorMessage").HasMaxLength(2048).HasColumnType("TEXT");
                b.HasKey("PodcastId");
                b.HasIndex("FileHash").IsUnique().HasDatabaseName("UX_Episodes_FileHash");
                b.HasIndex("UploadStatus").HasDatabaseName("IX_Episodes_UploadStatus");
                b.HasIndex("CreatedAt").HasDatabaseName("IX_Episodes_CreatedAt");
                b.ToTable("Episodes");
            });
#pragma warning restore 612, 618
        }
    }
}
